---
root: true
extends:
  - eslint:recommended
  - plugin:react/recommended
plugins:
  - react
parserOptions:
  sourceType: module
env:
  browser: true
  es2022: true
settings:
  react:
    version: detect
rules:
  eol-last:
    - error
    - always
  eqeqeq:
    - error
    - smart
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  no-tabs:
    - error
    - allowIndentationTabs: false
  no-trailing-spaces: error
  no-var: error
  prefer-const:
    - error
    - destructuring: any
      ignoreReadBeforeAssign: false
